import type { RequiredDataFromCollectionSlug } from 'payload'

export const contactForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Ubuntu Logistics Contact & Inquiry Form',
  submitButtonLabel: 'Send Inquiry',
  confirmationType: 'message',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Inquiry Received! Thank You.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h3',
          version: 1,
        },
        {
          type: 'paragraph',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Our Ubuntu Logistics operations desk has received your request. One of our transport coordinators will contact you via phone or email within 30 minutes with a quotation or assistance.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          textFormat: 0,
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  fields: [
    {
      name: 'full-name',
      blockName: 'full-name',
      blockType: 'text',
      label: 'Full Name',
      required: true,
      width: 50,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email Address',
      required: true,
      width: 50,
    },
    {
      name: 'phone',
      blockName: 'phone',
      blockType: 'text',
      label: 'Phone Number (with country code)',
      required: true,
      width: 50,
    },
    {
      name: 'service',
      blockName: 'service',
      blockType: 'select',
      label: 'Service of Interest',
      required: false,
      width: 50,
      options: [
        { label: 'Airport & Hotel Transfers', value: 'airport-hotel-transfers' },
        { label: 'Tours & Safari Transport (4x4)', value: 'tours-and-safari-transport' },
        { label: 'Car Hire & Chauffeur Rental', value: 'car-hire-and-rental-services' },
        { label: 'Corporate & Staff Transport', value: 'corporate-and-staff-transport' },
        { label: 'VIP & Executive Transport', value: 'vip-and-executive-transport' },
        { label: 'Event & Special Occasion Transport', value: 'event-and-special-occasion-transport' },
        { label: 'Handicap Accessible Mobility', value: 'handicap-accessible' },
        { label: 'Other Inquiries / Freight', value: 'other' },
      ],
    },
    {
      name: 'travel-date',
      blockName: 'travel-date',
      blockType: 'text',
      label: 'Expected Travel / Pickup Date',
      required: false,
      width: 50,
    },
    {
      name: 'passengers',
      blockName: 'passengers',
      blockType: 'number',
      label: 'Number of Passengers',
      required: false,
      width: 50,
    },
    {
      name: 'message',
      blockName: 'message',
      blockType: 'textarea',
      label: 'Trip Details / Special Requirements',
      required: true,
      width: 100,
    },
  ],
  emails: [
    {
      emailFrom: '"Ubuntu Logistics" <info@ubuntulogistics.co.ke>',
      emailTo: 'info@ubuntulogistics.co.ke',
      subject: 'New Ubuntu Logistics Website Inquiry: {{full-name}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'You received a new inquiry from the Ubuntu Logistics website contact form. Customer: {{full-name}}, Email: {{email}}, Phone: {{phone}}.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    {
      emailFrom: '"Ubuntu Logistics" <info@ubuntulogistics.co.ke>',
      emailTo: '{{email}}',
      subject: 'Thank you for contacting Ubuntu Logistics',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Dear {{full-name}}, thank you for reaching out to Ubuntu Logistics. Our operations team has received your message and will respond shortly.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
  ],
}
